In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sentences=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sentences

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Vocabulary size
voc_size=10000

In [8]:
#One Hot Representation
onehot_repr=[one_hot(words,voc_size)for words in sentences] 
print(onehot_repr)

[[6841, 9671, 4244, 7740], [6841, 9671, 4244, 1638], [6841, 9849, 4244, 1250], [9785, 2755, 1292, 7196, 6439], [9785, 2755, 1292, 7196, 6474], [2273, 6841, 6086, 4244, 2469], [3789, 8082, 2982, 7196]]


# Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

# Zeros would get padded before each sentence with the "pre" against the sentance length

[[   0    0    0    0 6841 9671 4244 7740]
 [   0    0    0    0 6841 9671 4244 1638]
 [   0    0    0    0 6841 9849 4244 1250]
 [   0    0    0 9785 2755 1292 7196 6439]
 [   0    0    0 9785 2755 1292 7196 6474]
 [   0    0    0 2273 6841 6086 4244 2469]
 [   0    0    0    0 3789 8082 2982 7196]]


In [11]:
# 10 Dimesnsions, how many feature representations that we have to go ahead with the model.
# But maximum what we have in this example is 5
dim=10

model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 6841, 9671, 4244, 7740])

In [15]:
# Each index value above is converted into 10 dimensilnal vector
print(model.predict(embedded_docs)[0])

[[ 0.01692558  0.02958528 -0.04168874 -0.03590534  0.00576282 -0.04427169
   0.00328482  0.00748748  0.04434054  0.0380713 ]
 [ 0.01692558  0.02958528 -0.04168874 -0.03590534  0.00576282 -0.04427169
   0.00328482  0.00748748  0.04434054  0.0380713 ]
 [ 0.01692558  0.02958528 -0.04168874 -0.03590534  0.00576282 -0.04427169
   0.00328482  0.00748748  0.04434054  0.0380713 ]
 [ 0.01692558  0.02958528 -0.04168874 -0.03590534  0.00576282 -0.04427169
   0.00328482  0.00748748  0.04434054  0.0380713 ]
 [ 0.02599872 -0.00915391  0.0349955  -0.01730018 -0.00505114 -0.02712944
   0.00281264 -0.01819197 -0.01113494 -0.04857565]
 [-0.02851652  0.04116266 -0.03203435  0.04264292  0.04125823 -0.00943381
   0.01272911 -0.00126464 -0.01307512 -0.0094    ]
 [ 0.03204546 -0.01215342 -0.04241891  0.01301033  0.00972012 -0.00925792
  -0.00666637 -0.00440861 -0.02554154 -0.01243697]
 [-0.02644029  0.01865442  0.04388313  0.04163868 -0.01599318  0.02246347
   0.01227482 -0.02176795  0.04111122  0.03052277]]